name: cupertino_store
description: Creating a Store in Cupertino widgets
version: 1.0.0+1

environment:
  sdk: ^2.4.0
  flutter: ^1.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  intl: ^0.15.7
  provider: ^3.0.0+1
  shrine_images: ^1.0.0

dev_dependencies:
  pedantic: ^1.8.0
  cupertino_icons: ^0.1.0

flutter:
